Repository tryber/sd-04-recipes-app-3, pull requests merged in 2020-08, with the labels that each got.

#23 components/Footer
  package.json
  public/index.html
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: Menu inferior, Tela principal de receitas

#24 Header/search bar
  package-lock.json
  package.json
  src/App.js
  src/actions/actionsType.js
  src/actions/apiRequest.js
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBtn.jsx
  src/components/SearchBar/SearchInput.jsx
  src/components/SearchBar/SearchRadio.jsx
  src/index.js
  src/reducers/apiRequest.js
  src/reducers/index.js
  src/services/requestAPI.js
  src/store/index.js
Labels: Filtros, Header

#25 Validação de formulário no local storage
  src/App.js
  src/helpers/index.js
  src/pages/LoginScreen.js
  src/pages/MealsScreen.js
Labels: Local Storage, Tela de login

#26 components/Header
  .eslintrc
  .stylelintrc.json
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/LoginScreen.js
  src/pages/MealsScreen.js
  src/pages/loginScreen.js
Labels: Header

#29 Header R-9/10/11/12
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBtn.jsx
Labels: Header

#30 SearchBar - R16/17/18
  src/App.js
  src/actions/actionsType.js
  src/actions/apiRequest.js
  src/components/SearchBar/SearchBtn.jsx
  src/pages/DetailsScreen/DetailsScreen.jsx
  src/pages/DetailsScreen/EmbeddedVideo.jsx
  src/pages/DetailsScreen/IngredientsList.jsx
  src/reducers/apiRequest.js
  src/reducers/recRequest.js
Labels: Barra de busca - Header

#33 Main screen
  src/components/Footer/Footer.jsx
  src/components/MainScreen/CategotyFilter.jsx
  src/components/MainScreen/ItemCard.jsx
  src/components/Recommendations/Recommendations.jsx
  src/components/SearchBar/SearchBtn.jsx
  src/css/Footer.css
  src/css/Header.css
  src/pages/DetailsScreen.js
  src/pages/DrinksScreen.js
  src/pages/LoginScreen.js
  src/pages/MealsScreen.js
  src/reducers/apiRequest.js
  src/reducers/recRequest.js
  src/services/requestAPI.js
Labels: Tela principal de receitas
